#Bienvenidos a la mentoría: 
##"Ciencia de datos aplicada al estudio de la Obesidad y otras enfermedades crónicas en Córdoba."


##### Como primer objetivo proponemos acercarnos a la temática propuesta presentando una breve introducción de la misma y sus posibles determinantes.


##Descripción del problema
La obesidad es una enfermedad crónica multicausal de alta prevalencia en el mundo y Argentina. La misma se encuentra en constante aumento y en Córdoba son más del 50% las personas que presentan exceso de peso, y un 25% del total obesidad. Si bien se piensa que los principales factores que influyen en su desarrollo, son un nivel de actividad física inadecuado, el sedentarismo y una alimentación poco saludable, pueden existir otros determinantes de esta condición que deban ser considerados. Sin embargo, muchas veces es difícil contar con todos estos datos y analizarlos de manera conjunta  o considerando su efecto sinérgico.
Por otra parte, al conocer los aspectos que más influyen en la ocurrencia de esta enfermedad se podría abordar de manera integral y ofrecer a la población información, realizar recomendaciones y utilizar estos resultados para implementar políticas públicas para enfrentar la pandemia de la obesidad.
Así, en esta mentoría ponemos a disposición un dataset que tiene una numerosa variedad de features las cuales permitirán poder seleccionar aquellos que sean los mejores predictores para la enfermedad. También identificar patrones de alimentación y subgrupos de sujetos que compartan ciertas características, y de esta forma descubrir nuevos insights para desarrollar.   
Además, resulta interesante desarrollar metodologías para analizar y describir este problema, las que pueden ser replicadas en otros de las Ciencias de la salud y en el que se utilicen principalmente las herramientas que la Ciencia de Datos provee.
Esperamos que en esta mentoría puedas desarrollar y aplicar todas las herramientas y skills aprendidas durante el cursado de la diplomatura. Te proponemos objetivos específicos para la resolución de cada práctico poniendo en juego tus conocimientos y creatividad, y quién te dice encontras tu lado Abby Sciuto/John Snow. 


##Motivación
❖	¿Cuáles son las principales características de la población de Córdoba en cuanto a sus determinantes bio-socio-económicos?

❖	¿Es la obesidad una enfermedad que depende meramente de la alimentación de los sujetos?

❖	¿Cuáles son los factores alimentarios que promueven el desarrollo de la enfermedad?¿Y cuáles son aquellos que protegen?

❖	¿Se encuentra la obesidad asociada a la enfermedad cardiovascular?¿y al cáncer?

❖	¿Qué variables ayudarían a predecir el estado nutricional de un sujeto de la población de Córdoba?

❖	¿Cuáles son las características más visibles de los grupos según su estado nutricional?¿Existen características comunes que nos permitan predecir el estado nutricional que tendrá una persona?

❖	¿Existe algún patrón alimentario característico por grupos según la presencia o no de obesidad?






# **Práctico N°4**           **Aprendizaje Supervisado**

## Objetivo y alcance




A partir del práctico anterior, el cual fue un primer acercamiento al proceso de aprendizaje automático, trabajaremos exclusivamente en el aprendizaje supervisado. Anteriormente han trabajado prediciendo la "obesidad" pero ahora cambiaremos la variable respuesta y pondremos atención en los algoritmos y técnicas.
Nos enfocaremos en el proceso de: selección de un modelo, ajuste de hiperparámetros y evaluación, regulador, métricas, similar a lo hecho previamente.
En este laboratorio no se espera que se encuentre el mejor modelo con sus mejores parámetros, sino que se logre la buena práctica de realizar los pasos necesarios en un proceso de aprendizaje automático, desde la división del dataset hasta la evaluación del modelo, además de aplicar las sugerencias o cambios recomendados en la devolución del lab 3. Por ello podemos decir que el objetivo del práctico es indagar entre los diferentes modelos de aprendizaje supervisado vistos en la materia y comparar el desempeño obtenido. Para realizar el práctico vamos a utilizar el dataset generado en el lab 2 y luego, a partir de lo realizado en el práctico de introducción al aprendizaje automático, cambiar y probar otros modelos vistos en esta materia y comparar los resultados a partir de la métrica seleccionada(la/s misma/s para los diferentes modelos). 


### **La necesidad es la siguiente:**

1.   Poder predecir de forma automática la presencia de HTA en toda la población. Trabajaremos con la variable "HTA" dado que tiene en cuenta no sólo la declaración de hipertensión por la persona, sino que también si consumen medicación para la misma o al tomar la tensión dió elevada.
2.   Poder predecir de forma automática la presencia de HTA en mujeres (grupo 1: Martin, Fer y Memi) y en hombres (grupo 2: Nico, Fer y Edgardo).
3. Poder determinar cuales son las variables que son consideradas factores de riesgo para presentar HTA, tanto para toda la población como discriminando por sexos (cada grupo lo hace para el sexo que les haya tocado).

### **Para ello se debe:**

* Cargar los datos, separando del dataset la etiqueta a predecir.
* Dividir el dataset en el conjunto de entrenamiento y conjunto de test
*   Analizar y justificar que features se utilizarán para lograr la mejor predicción.
*   Elegir un modelo de clasificación clásico (por cada requerimiento). El que Uds. se sientan más cómodos, pero también justificando conceptualmente la elección del mismo. Y por otro lado, realizar otro modelo utilizando una técnica de ensemble (bagging, boosting) también justificando la elección del mismo.
*   Entrenar y evaluar los modelos, fijando la semilla aleatoria para hacer repetible el experimento.
*   En cuanto a los hiper-parámetros:

        1.   Probar primero con los default y elegir alguna/s métrica/s para reportar los resultados. 
        2.   Luego usar grid-search y 5-fold cross-validation para explorar muchas combinaciones posibles de valores, reportando  accuracy promedio y varianza para todas las configuraciones.

*   Para la mejor configuración encontrada, evaluar sobre el conjunto de entrenamiento y sobre el conjunto de evaluación, reportando:
        *   Accuracy
        *   Precision
        *   Recall
        *   F1
        *   Matriz de confusión

### Se evaluarán los siguientes aspectos:
  ***1-*** Que se apliquen los conceptos vistos con los profes en el teórico y en el práctico.

  ***2-*** Que el entregable no sea solo la notebook. El informe debe tener un mensaje claro y debe presentarse en un formato legible para cualquier tipo de stakeholder.

  ***3-*** Capacidad de análisis.

  ***4-*** Criterio para elegir que solución aplicar en cada caso y con qué método implementarla.

##Recuerden que las clases a clasificar están desbalanceadas.

  
## Deadline pautado para la entrega: Lunes 13/09/2020




## Estructura del informe
El informe debe estar en un formato que no sea Jupyter Notebook, por ejemplo .html, .pdf, .md. El objetivo es poder redactar y justificar las conclusiones obtenidas a partir de las preguntas disparadoras, utilizando material gráfico y/o interactivo como soporte para complementar las ideas. 
Además, se debe presentar o enviar la notebook en donde se trabajó (jupyter notebook, colab notebook, etc).  

###Se evaluarán los siguientes aspectos:
Que se apliquen los conceptos vistos en el dictado de la materia.

El informe debe tener un mensaje claro y debe presentarse en un formato legible para cualquier tipo de stakeholder.

Que los cálculos estadísticos sean utilizados solo como herramientas para responder a las consignas.

Indicar el criterio aplicado al momento de elegir las variables a analizar.


#### HTA == 1: sin hipertensión
#### HTA == 2: con hipertensión

#### sexo == 0: mujeres
#### sexo == 1 hombres

In [ ]:
from sklearn.metrics            import (accuracy_score, 
                                       precision_score,
                                       recall_score, 
                                       f1_score, 
                                       confusion_matrix)
from sklearn.model_selection    import train_test_split
import numpy as np
import pandas as pd
from sklearn.tree               import DecisionTreeClassifier
from sklearn.dummy              import DummyClassifier
from sklearn.naive_bayes        import MultinomialNB
from sklearn.linear_model       import SGDClassifier
from sklearn.ensemble           import RandomForestClassifier, VotingClassifier, GradientBoostingClassifier
from sklearn.neighbors          import KNeighborsClassifier
from sklearn.linear_model       import Perceptron
from sklearn.model_selection    import GridSearchCV, RandomizedSearchCV

In [ ]:
def print_grid_results(df, dict, rows=5):
  df = df.sort_values(by='rank_test_score').head(rows)
  param = ['rank_test_score', 'mean_test_score']
  for i in dict.keys():
    param.append('param_'+str(i))
  new_df = df.loc[:, param]
  return new_df

In [ ]:
def print_metrics(y_real, y_pred):
    accuracy = accuracy_score(y_real, y_pred)
    precision = precision_score(y_real, y_pred)
    recall = recall_score(y_real, y_pred)
    f1 = f1_score(y_real, y_pred)
    confusion = confusion_matrix(y_real, y_pred)

    print('accuracy: ', accuracy)
    print('precision: ', precision)
    print('recall :', recall)
    print('f1_score :', f1)
    print('matriz de confusión: \n',confusion)

In [ ]:
from   google.colab      import files
encuestas = files.upload()

Saving cured_data_obesity.csv to cured_data_obesity.csv


In [ ]:
df = pd.read_csv('cured_data_obesity.csv')

In [ ]:
# Generamos un vector para separar las features que vamos a utilizar en la predicción
# junto con la variable target (HTA) y sexo
hta_features = ['HTA'    , 'sexo'   , 'edad'   , 'dbt'     , 'tipo1'  , 'tipo2' ,
               'tratadbt',  'dlp'   , 'cc'     , 'actfis'  , 'nombre' , 'act'   ,
               'fve1'    , 'fve2'   , 'fgr1'   , 'fgs1'    , 'fgs2'   , 'fgp1'  , 
               'fgm1'    , 'fgm2'   , 'fcol1'  , 'fcol2'   , 'fgp2'   , 'mets'  ,
               'fuma'    , 'durac'  , 'stress'                                  ]

In [ ]:
# separamos las observaciones que se van a utilizar
# para la predicción (X) y la variable target HTA (y)

df = df[hta_features]
df = df.dropna()

X_mujeres  = df[df.sexo == 0].drop('HTA', axis=1)
y_mujeres  = df[df.sexo == 0].HTA

X_todos    = df.drop('HTA', axis=1)
y_todos    = df.HTA

In [ ]:
# separamos el 20% de los datos para el conjunto test
X_mujeres_train , X_mujeres_test , y_mujeres_train , y_mujeres_test = train_test_split(X_mujeres , y_mujeres , test_size=0.2 , random_state=5)
X_todos_train   , X_todos_test   , y_todos_train   , y_todos_test   = train_test_split(X_todos   , y_todos   , test_size=0.2 , random_state=5)

In [ ]:
random_state  = 5
dict_models   =  {'DecisionTreeClassifier' : DecisionTreeClassifier(random_state=random_state),
                  'KNeighborsClassifier'   : KNeighborsClassifier(),
                  'SGDClassifier'          : SGDClassifier(random_state=random_state),
                  'Perceptron'             : Perceptron(),
                  'MultinomialNB'          : MultinomialNB(),
                  'Dummy_frequent'         : DummyClassifier(strategy='most_frequent'),
                  'Dummy_stratified'       : DummyClassifier(strategy= 'stratified', random_state=random_state),
                  'RandomForestClassifier' : RandomForestClassifier(random_state=random_state)
                 }

In [ ]:
# probamos con algunos modelos con valores por defecto
dict_acc = {}
c = 0
for i in dict_models.keys():
  model =       dict_models[i]
  model.fit(X_mujeres_train, y_mujeres_train)
  y_pred =      model.predict(X_mujeres_test)
  dict_acc[i] = accuracy_score(y_mujeres_test, y_pred)
  print('****** ' + str(i) + ' ******') 
  print_metrics(y_mujeres_test, y_pred)
  print('\n')
  c += 1

****** DecisionTreeClassifier ******
accuracy:  0.6794871794871795
precision:  0.7896440129449838
recall : 0.7416413373860182
f1_score : 0.7648902821316613
matriz de confusión: 
 [[244  85]
 [ 65  74]]


****** KNeighborsClassifier ******
accuracy:  0.6602564102564102
precision:  0.7225130890052356
recall : 0.8389057750759878
f1_score : 0.7763713080168776
matriz de confusión: 
 [[276  53]
 [106  33]]


****** SGDClassifier ******
accuracy:  0.7094017094017094
precision:  0.7093275488069414
recall : 0.993920972644377
f1_score : 0.8278481012658226
matriz de confusión: 
 [[327   2]
 [134   5]]


****** Perceptron ******
accuracy:  0.6987179487179487
precision:  0.7136363636363636
recall : 0.9544072948328267
f1_score : 0.8166449934980494
matriz de confusión: 
 [[314  15]
 [126  13]]


****** MultinomialNB ******
accuracy:  0.4829059829059829
precision:  0.7351351351351352
recall : 0.4133738601823708
f1_score : 0.5291828793774319
matriz de confusión: 
 [[136 193]
 [ 49  90]]


****** Dummy_

In [ ]:
dict_acc = {}
c = 0
for i in dict_models.keys():
  model =       dict_models[i]
  model.fit(X_todos_train, y_todos_train)
  y_pred =      model.predict(X_todos_test)
  dict_acc[i] = accuracy_score(y_todos_test, y_pred)
  print('****** ' + str(i) + ' ******') 
  print_metrics(y_todos_test, y_pred)
  print('\n')
  c += 1

****** DecisionTreeClassifier ******
accuracy:  0.6573248407643312
precision:  0.7549407114624506
recall : 0.7248576850094877
f1_score : 0.739593417231365
matriz de confusión: 
 [[382 145]
 [124 134]]


****** KNeighborsClassifier ******
accuracy:  0.643312101910828
precision:  0.7054908485856906
recall : 0.8045540796963947
f1_score : 0.75177304964539
matriz de confusión: 
 [[424 103]
 [177  81]]


****** SGDClassifier ******
accuracy:  0.6764331210191082
precision:  0.7034277198211625
recall : 0.8956356736242884
f1_score : 0.7879799666110184
matriz de confusión: 
 [[472  55]
 [199  59]]


****** Perceptron ******
accuracy:  0.7057324840764331
precision:  0.7151162790697675
recall : 0.9335863377609108
f1_score : 0.8098765432098766
matriz de confusión: 
 [[492  35]
 [196  62]]


****** MultinomialNB ******
accuracy:  0.5337579617834395
precision:  0.7766323024054983
recall : 0.428842504743833
f1_score : 0.5525672371638142
matriz de confusión: 
 [[226 301]
 [ 65 193]]


****** Dummy_freq

In [ ]:
dict_tree = {'criterion':             ['gini', 'entropy'],
             'min_samples_split':     [2, 10, 50, 100, 200, 500],
             'max_features':          [None, 'auto', 'sqrt', 'log2'],
            }

model =     DecisionTreeClassifier(random_state=10)
clf =       RandomizedSearchCV(model, dict_tree, scoring='accuracy')
search =    clf.fit(X_mujeres_train, y_mujeres_train)
search_df = pd.DataFrame(search.cv_results_)

In [ ]:
print_grid_results(search_df, dict_tree)

rank_test_score  mean_test_score  ... param_min_samples_split param_max_features
3                1         0.733006  ...                     200               None
5                2         0.723369  ...                      50               None
9                3         0.715349  ...                      50               auto
6                4         0.705717  ...                     500               sqrt
4                5         0.703039  ...                     500               log2

[5 rows x 5 columns]

In [ ]:
model = DecisionTreeClassifier(criterion='entropy', min_samples_split=100,
                               max_features=None, random_state=10)
clf_tree = model.fit(X_mujeres_train, y_mujeres_train)
y_pred = clf_tree.predict(X_mujeres_test)
print_metrics(y_mujeres_test, y_pred)

accuracy:  0.7478632478632479
precision:  0.8093841642228738
recall : 0.8389057750759878
f1_score : 0.8238805970149254
matriz de confusión: 
 [[276  53]
 [ 65  74]]


In [ ]:
# Desicion Tree para mujeres
param_map = { 'criterion'        : ['gini','entropy'],
              'splitter'         : ['best','random'],
              'max_depth'        : list(range(2, 40, 1)) + [None],
              'min_samples_leaf' : range(1,40, 2),
              'min_samples_split': [2, 10, 50, 100, 200, 500],
              'max_features'     : [None,'auto','sqrt','log2'] 
}

DTclassifier  = DecisionTreeClassifier(random_state = 0)

grid_search = GridSearchCV(DTclassifier, param_map, n_jobs=-1, scoring = 'accuracy', cv= None) # By default it uses 5 fold validation
grid_search.fit(X_mujeres_train, y_mujeres_train)

best_model = grid_search.best_estimator_
print(best_model)

DTclassifier = best_model.fit(X_mujeres_train, y_mujeres_train)
y_mujeres_pred = best_model.predict(X_mujeres_test)
print_metrics(y_mujeres_test, y_mujeres_pred)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=17, min_samples_split=100,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='random')
accuracy:  0.7414529914529915
precision:  0.8270440251572327
recall : 0.7993920972644377
f1_score : 0.8129829984544049
matriz de confusión: 
 [[263  66]
 [ 55  84]]


In [ ]:
# Clasificador gradiente para mujeres 
gradient = SGDClassifier(random_state=5)

gradient.fit(X_mujeres_train, y_mujeres_train)
y_pred = gradient.predict(X_mujeres_test)
print_metrics(y_mujeres_test, y_pred)

gradient_param_map  = { 'loss'          : ['hinge', 'log', 'squared_hinge'] ,
                        'penalty'       : ['l2','l1','elasticnet']          ,
                        'warm_start'    : [True,False]                      ,
                        'alpha'         : [0.00001, 0.000001, 0.0000001]    ,
                        'average'       : [True, False]
                    }

gradient = SGDClassifier(random_state=5)
gradient_grid_search = GridSearchCV(gradient, gradient_param_map, scoring='accuracy', n_jobs = 4)
gradient_grid_search.fit(X_mujeres_train, y_mujeres_train)
best_clf = gradient_grid_search.best_estimator_
print(best_clf)
SGD_mujeres = best_clf.fit(X_mujeres_train, y_mujeres_train)
y_pred = best_clf.predict(X_mujeres_test)
print ("Resultado gradiente de mujeres")
print_metrics(y_mujeres_test, y_pred)

accuracy:  0.7094017094017094
precision:  0.7093275488069414
recall : 0.993920972644377
f1_score : 0.8278481012658226
matriz de confusión: 
 [[327   2]
 [134   5]]
SGDClassifier(alpha=1e-06, average=True, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l1', power_t=0.5,
              random_state=5, shuffle=True, tol=0.001, validation_fraction=0.1,
              verbose=0, warm_start=True)
Resultado gradiente de mujeres
accuracy:  0.7606837606837606
precision:  0.7908847184986595
recall : 0.8966565349544073
f1_score : 0.8404558404558403
matriz de confusión: 
 [[295  34]
 [ 78  61]]


In [ ]:
# Desicion tree todos
param_mapTODOS = { 'criterion'        : ['gini','entropy'],
              'splitter'         : ['best','random'],
              'max_depth'        : list(range(2, 20, 1)) + [None],
              'min_samples_leaf' : range(1,40, 2),
              'min_samples_split':     [2, 10, 50, 100, 200, 500],
              'max_features'     : [None,'auto','sqrt','log2'] 
}

DTclassifierTODOS  = DecisionTreeClassifier(random_state = 0)

grid_search = GridSearchCV(DTclassifierTODOS, param_mapTODOS, n_jobs=-1, scoring = 'accuracy', cv= None) # By default it uses 5 fold validation
grid_search.fit(X_todos_train, y_todos_train)

best_model = grid_search.best_estimator_
print(best_model)

DTclassifierTODOS = best_model.fit(X_todos_train, y_todos_train)
y_todos_pred = best_model.predict(X_todos_test)
print_metrics(y_todos_test, y_todos_pred)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='random')
accuracy:  0.7044585987261146
precision:  0.7757009345794392
recall : 0.7874762808349146
f1_score : 0.7815442561205272
matriz de confusión: 
 [[415 112]
 [120 138]]


In [ ]:
# Clasificador gradiente para todos
gradient = SGDClassifier(random_state=5)

gradient.fit(X_todos_train, y_todos_train)
y_pred = gradient.predict(X_todos_test)
print_metrics(y_todos_test, y_pred)

gradient_param_map  = { 'loss'          : ['hinge', 'log', 'squared_hinge'] ,
                        'penalty'       : ['l2','l1','elasticnet']          ,
                        'warm_start'    : [True,False]                      ,
                        'alpha'         : [0.00001, 0.000001, 0.0000001]    ,
                        'average'       : [True, False]
                    }

gradient = SGDClassifier(random_state=5)
gradient_grid_search = GridSearchCV(gradient, gradient_param_map, scoring='accuracy', n_jobs = 4)
gradient_grid_search.fit(X_todos_train, y_todos_train)
best_clf = gradient_grid_search.best_estimator_
print(best_clf)
SGD_todos = best_clf.fit(X_todos_train, y_todos_train)
y_pred = best_clf.predict(X_todos_test)
print ("Resultado gradiente de todos")
print_metrics(y_todos_test, y_pred)

accuracy:  0.6764331210191082
precision:  0.7034277198211625
recall : 0.8956356736242884
f1_score : 0.7879799666110184
matriz de confusión: 
 [[472  55]
 [199  59]]
SGDClassifier(alpha=1e-06, average=True, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='squared_hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l1',
              power_t=0.5, random_state=5, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=True)
Resultado gradiente de todos
accuracy:  0.7133757961783439
precision:  0.745928338762215
recall : 0.8690702087286527
f1_score : 0.8028045574057844
matriz de confusión: 
 [[458  69]
 [156 102]]


In [ ]:
# Ahora pasamos los meta modelos.
# Random forest para mujeres
random_forest = RandomForestClassifier(random_state = 5)

random_forest.fit(X_mujeres_train, y_mujeres_train)
y_pred = random_forest.predict(X_mujeres_test)
print_metrics(y_mujeres_test, y_pred)

forest_param_map  = {   'n_estimators'      : [120, 125, 130]    ,
                        'criterion'         : ['gini','entropy'] ,
                        'warm_start'        : [True,False]       ,
                        'max_depth'         : [20, 25, 30]       ,
                        'min_samples_split' : [3, 4, 5]          ,
                        'min_samples_leaf'  : [2, 3, 4]          ,
                        'max_features'      : [None, 'auto','log2']
                    }

random_forest = RandomForestClassifier(random_state = 5)
forest_grid_search = GridSearchCV(random_forest, forest_param_map, scoring='accuracy', n_jobs = 4)
forest_grid_search.fit(X_mujeres_train, y_mujeres_train)
best_clf = forest_grid_search.best_estimator_
print(best_clf)
RF_mujeres = best_clf.fit(X_mujeres_train, y_mujeres_train)
y_pred = best_clf.predict(X_mujeres_test)
print ("Resultado arbol de mujeres")
print_metrics(y_mujeres_test, y_pred)

accuracy:  0.7777777777777778
precision:  0.8205128205128205
recall : 0.8753799392097265
f1_score : 0.8470588235294118
matriz de confusión: 
 [[288  41]
 [ 63  76]]
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=20, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, n_estimators=120,
                       n_jobs=None, oob_score=False, random_state=5, verbose=0,
                       warm_start=True)
Resultado arbol de mujeres
accuracy:  0.7735042735042735
precision:  0.8140845070422535
recall : 0.878419452887538
f1_score : 0.8450292397660819
matriz de confusión: 
 [[289  40]
 [ 66  73]]


/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_forest.py:359: UserWarning: Warm-start fitting without increasing n_estimators does not fit new trees.
  warn("Warm-start fitting without increasing n_estimators does not "


In [ ]:
# Random forest para todos
random_forest = RandomForestClassifier(random_state = 5)

random_forest.fit(X_todos_train, y_todos_train)
y_pred = random_forest.predict(X_todos_test)
print_metrics(y_todos_test, y_pred)

forest_param_map  = {   'n_estimators'      : [120, 125, 130]    ,
                        'criterion'         : ['gini','entropy'] ,
                        'warm_start'        : [True,False]       ,
                        'max_depth'         : [20, 25, 30]       ,
                        'min_samples_split' : [3, 4, 5]          ,
                        'min_samples_leaf'  : [2, 3, 4]          ,
                        'max_features'      : [None, 'auto','log2']
                    }

random_forest = RandomForestClassifier(random_state = 5)
forest_grid_search = GridSearchCV(random_forest, forest_param_map, scoring='accuracy', n_jobs = 4)
forest_grid_search.fit(X_todos_train, y_todos_train)
best_clf = forest_grid_search.best_estimator_
print(best_clf)
RF_todos = best_clf.fit(X_todos_train, y_todos_train)
y_pred = best_clf.predict(X_todos_test)
print ("Resultado arbol de todos")
print_metrics(y_todos_test, y_pred)

accuracy:  0.710828025477707
precision:  0.759515570934256
recall : 0.8330170777988615
f1_score : 0.7945701357466063
matriz de confusión: 
 [[439  88]
 [139 119]]
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=30, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, n_estimators=130,
                       n_jobs=None, oob_score=False, random_state=5, verbose=0,
                       warm_start=True)
Resultado arbol de todos
accuracy:  0.7273885350318471
precision:  0.7693631669535284
recall : 0.8481973434535104
f1_score : 0.8068592057761732
matriz de confusión: 
 [[447  80]
 [134 124]]


/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_forest.py:359: UserWarning: Warm-start fitting without increasing n_estimators does not fit new trees.
  warn("Warm-start fitting without increasing n_estimators does not "


In [ ]:
# Ahora hacemos un voting classifier
model = VotingClassifier(estimators=[('tree', DTclassifier),
                                     ('forest', RF_mujeres),
                                     ('gradient', SGD_mujeres)],
                         voting='soft')
clf_v = model.fit(X_mujeres_train, y_mujeres_train)
y_pred = clf_v.predict(X_mujeres_test)
print_metrics(y_mujeres_test, y_pred)

accuracy:  0.7628205128205128
precision:  0.7868421052631579
recall : 0.9088145896656535
f1_score : 0.8434414668547251
matriz de confusión: 
 [[299  30]
 [ 81  58]]


In [ ]:
# Ahora hacemos un voting classifier
model = VotingClassifier(estimators=[('tree', DTclassifierTODOS),
                                     ('forest', RF_todos),
                                     ('gradient', SGD_mujeres)],
                         voting='soft')
clf_v = model.fit(X_todos_train, y_todos_train)
y_pred = clf_v.predict(X_todos_test)
print_metrics(y_todos_test, y_pred)


accuracy:  0.7095541401273885
precision:  0.7415185783521809
recall : 0.8709677419354839
f1_score : 0.8010471204188481
matriz de confusión: 
 [[459  68]
 [160  98]]
